dist: bionic

language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
go:
  - 1.13.x

git:
  depth: 1

install: true

notifications:
  email: false

script:
  - make test targets
